### ISSUE TITLE
Please add ModRiskFileTypes

### ISSUE THREAD

**Issue by ropean** [m2nlight/WindowsServerToWindowsDesktop#1]
Your project is very useful for me, thanks.

Please add ModRiskFileTypes, the command is follow:

reg add HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Associations /v ModRiskFileTypes /t REG_SZ /d .bat;.exe;.reg;.vbs /f

**Comment by m2nlight** [comment]
Hi @ropean! Thanks for your advice. I checked this value in Win10, it isn't a default options. So, I will not add this. But, you can fork this repo for yours.
